// Authorization specific constants
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILRE';
export const HAS_TOKEN_SUCCESS = 'HAS_TOKEN_SUCCESS';
export const HAS_TOKEN_FAILURE = 'HAS_TOKEN_FAILURE';
