// Fetch all constants
export const FETCH_ALL_DEPARTMENTS_SUCCESS = 'FETCH_ALL_DEPARTMENTS_SUCCESS';
export const FETCH_ALL_DEPARTMENTS_FAILURE = 'FETCH_ALL_DEPARTMENTS_FAILURE';

// Fetch one constants
export const FETCH_SINGLE_DEPARTMENT_SUCCESS = 'FETCH_SINGLE_DEPARTMENT_SUCCESS';
export const FETCH_SINGLE_DEPARTMENT_FAILURE = 'FETCH_SINGLE_DEPARTMENT_FAILURE';

// Save constants
export const SAVE_DEPARTMENT_SUCCESS = 'SAVE_DEPARTMENT_SUCCESS';
export const SAVE_DEPARTMENT_FAILURE = 'SAVE_DEPARTMENT_FAILURE';

// Update constants
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';

// Delete constants
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';
