// Fetch all constants
export const FETCH_ALL_STUDENTS_SUCCESS = 'FETCH_ALL_STUDENTS_SUCCESS';
export const FETCH_ALL_STUDENTS_FAILURE = 'FETCH_ALL_STUDENTS_FAILURE';

// Fetch one constants
export const FETCH_SINGLE_STUDENT_SUCCESS = 'FETCH_SINGLE_STUDENT_SUCCESS';
export const FETCH_SINGLE_STUDENT_FAILURE = 'FETCH_SINGLE_STUDENT_FAILURE';

// Save constants
export const SAVE_SUBJECT_SUCCESS = 'SAVE_SUBJECT_SUCCESS';
export const SAVE_SUBJECT_FAILURE = 'SAVE_SUBJECT_FAILURE';

// Update constants
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_FAILURE = 'UPDATE_SUBJECT_FAILURE';

// Delete constants
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILURE = 'DELETE_SUBJECT_FAILURE';
