// Fetch all constants
export const FETCH_ALL_SUBJECTS_SUCCESS = 'FETCH_ALL_SUBJECTS_SUCCESS';
export const FETCH_ALL_SUBJECTS_FAILURE = 'FETCH_ALL_SUBJECTS_FAILURE';

// Fetch one constants
export const FETCH_SINGLE_SUBJECT_SUCCESS = 'FETCH_SINGLE_SUBJECT_SUCCESS';
export const FETCH_SINGLE_SUBJECT_FAILURE = 'FETCH_SINGLE_SUBJECT_FAILURE';

// Save constants
export const SAVE_SUBJECT_SUCCESS = 'SAVE_SUBJECT_SUCCESS';
export const SAVE_SUBJECT_FAILURE = 'SAVE_SUBJECT_FAILURE';

// Update constants
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_FAILURE = 'UPDATE_SUBJECT_FAILURE';

// Delete constants
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILURE = 'DELETE_SUBJECT_FAILURE';
