// Fetch all constants
export const FETCH_ALL_BOARDS_SUCCESS = 'FETCH_ALL_BOARDS_SUCCESS';
export const FETCH_ALL_BOARDS_FAILURE = 'FETCH_ALL_BOARDS_FAILURE';

// Fetch one constants
export const FETCH_SINGLE_BOARD_SUCCESS = 'FETCH_SINGLE_BOARD_SUCCESS';
export const FETCH_SINGLE_BOARD_FAILURE = 'FETCH_SINGLE_BOARD_FAILURE';

// Save constants
export const SAVE_BOARD_SUCCESS = 'SAVE_BOARD_SUCCESS';
export const SAVE_BOARD_FAILURE = 'SAVE_BOARD_FAILURE';

// Update constants
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';
export const UPDATE_BOARD_FAILURE = 'UPDATE_BOARD_FAILURE';

// Delete constants
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE';
