// Fetch all constants
export const FETCH_ALL_TUTORS_SUCCESS = 'FETCH_ALL_TUTORS_SUCCESS';
export const FETCH_ALL_TUTORS_FAILURE = 'FETCH_ALL_TUTORS_FAILURE';

// Fetch one constants
export const FETCH_SINGLE_TUTOR_SUCCESS = 'FETCH_SINGLE_TUTOR_SUCCESS';
export const FETCH_SINGLE_TUTOR_FAILURE = 'FETCH_SINGLE_TUTOR_FAILURE';

// Save constants
export const SAVE_TUTOR_SUCCESS = 'SAVE_TUTOR_SUCCESS';
export const SAVE_TUTOR_FAILURE = 'SAVE_TUTOR_FAILURE';

// Update constants
export const UPDATE_TUTOR_SUCCESS = 'UPDATE_TUTOR_SUCCESS';
export const UPDATE_TUTOR_FAILURE = 'UPDATE_TUTOR_FAILURE';

// Delete constants
export const DELETE_TUTOR_SUCCESS = 'DELETE_TUTOR_SUCCESS';
export const DELETE_TUTOR_FAILURE = 'DELETE_TUTOR_FAILURE';
